In [2]:
import numpy as np

np.array(10)

np.array([1,2])

np.array([[1,2],[3,4]])

np.array([[  [1,2],[3,4]  ] , [   [5,6],[7,8]  ]  ])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=3)

print(arr.ndin)
print(arr.shape)

AttributeError: 'numpy.ndarray' object has no attribute 'ndin'

In [1]:
import numpy as np

arr=np.zeros((3,1,5))
print(arr)

[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]]


In [12]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [17]:
arr=np.arange(10,21,4)
print(arr)

[10 14 18]


In [21]:
arr=np.array([2,4,5,1,7,6,9,8,10])
sorted_array=np.sort(arr)
print(sorted_array)

[ 1  2  4  5  6  7  8  9 10]


In [24]:
arr=np.array(['koshka','dingo','Ak47'])
sorted_array=np.sort(arr)
print(sorted_array)

['Ak47' 'dingo' 'koshka']


In [3]:

arr=np.array([[6,4,3],[9,5,6]])
print(np.sort(arr))



[[3 4 6]
 [5 6 9]]


In [20]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[-3:-1])

[2 3]


In [46]:
mat=np.array([ [[10,20,21],[23,22,25]],[[30,40,41],[42,43,45]] ])
print(mat)
print("Value:",mat[0,0,1])

[[[10 20 21]
  [23 22 25]]

 [[30 40 41]
  [42 43 45]]]
Value: 20


In [47]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:6:2])

[2 4 6]


In [49]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr[1,1:4])

[6 7 8]


In [55]:
arr=np.array([1,2,3,4,5])
x=np.where(arr%2==0)
print(x) 

(array([1, 3], dtype=int64),)


In [61]:
import numpy as np
arr=np.array([2,3,5,10])
x=np.searchsorted(arr,1)
print(x)

0


In [68]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x=arr.reshape(2,6)
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
import numpy as np
arr=np.array([10,30,20,60,70])
b=[True,False,False,False,True]
newarr=arr[b]
print(newarr)

[10 70]


In [7]:
arr=np.array([0,1,2,3,4,5,8,13])
result=filter(lambda input:input%2!=0,arr)
print(list(result))

[1, 3, 5, 13]


In [13]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(5,11).reshape(2,3)
print("B:",b)

c=np.concatenate((a,b))
print("Concatenated:",c)

d=np.arange(14,20).reshape(2,3)
print("D:",d)

A: [[0 1 2]
 [3 4 5]]
B: [[ 5  6  7]
 [ 8  9 10]]
Concatenated: [[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
D: [[14 15 16]
 [17 18 19]]


In [14]:
a=np.arange(6).reshape(2,3)
b=np.arange(5,11).reshape(2,3)

mat=np.concatenate((a,b),axis=1)
print(mat)

[[ 0  1  2  5  6  7]
 [ 3  4  5  8  9 10]]


In [17]:
stack_mat=np.stack((a,b))
stack_mat

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [19]:
mat=np.dstack((a,b))
mat[0,0,1]
print(mat)

[[[ 0  5]
  [ 1  6]
  [ 2  7]]

 [[ 3  8]
  [ 4  9]
  [ 5 10]]]


In [9]:
import pandas as pd
import numpy as np 
a=np.array([10,20,30,40,50])
s=pd.Series(a)
s


0    10
1    20
2    30
3    40
4    50
dtype: int32

In [5]:
import pandas as pd
data={"Roll_No":[101,102,103,104,105,106],
        "Student_Name":["Dp","Preetham","Hataf","Prathamesh","Chetan","Sameer"],
        "NS":[70,67,95,85,90,96],
        "JAVA":[88,72,80,60,99,82],
        "Total":[158,139,175,145,189,178]}
df=pd.DataFrame(data)
print(df)

   Roll_No Student_Name  NS  JAVA  Total
0      101           Dp  70    88    158
1      102     Preetham  67    72    139
2      103        Hataf  95    80    175
3      104   Prathamesh  85    60    145
4      105       Chetan  90    99    189
5      106       Sameer  96    82    178


In [6]:
print(df.loc[3])

Roll_No                104
Student_Name    Prathamesh
NS                      85
JAVA                    60
Total                  145
Name: 3, dtype: object


In [7]:
print(df.loc[0])
print(df.loc[1])
print(df.loc[5])


Roll_No         101
Student_Name     Dp
NS               70
JAVA             88
Total           158
Name: 0, dtype: object
Roll_No              102
Student_Name    Preetham
NS                    67
JAVA                  72
Total                139
Name: 1, dtype: object
Roll_No            106
Student_Name    Sameer
NS                  96
JAVA                82
Total              178
Name: 5, dtype: object


In [8]:
print(df[['Student_Name','Total']])

  Student_Name  Total
0           Dp    158
1     Preetham    139
2        Hataf    175
3   Prathamesh    145
4       Chetan    189
5       Sameer    178
